openapi: 3.0.0
info:
  title: BSS Web admin API
  version: 1.0.0
  contact:
    name: Bence Csik
    url: https://github.com/csikb
tags:
  - name: Member
    description: "REST operations for members"
  - name: Video
    description: "REST operations for videos"
  - name: VideoCrew
    description: "REST operations for video crews"
  - name: Event
    description: "REST operations for events"
  - name: EventVideo
    description: "REST operations for event videos"
  - name: Metrics
    description: "REST operations for metrics"
paths:
  /api/v1/member:
    get:
      summary: "Read all member"
      description: "Read all member"
      tags:
        - Member
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'
    post:
      summary: "Create member"
      description: "Create member"
      tags:
        - Member
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMember'
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
  /api/v1/member/{memberId}:
    put:
      summary: "Update member"
      description: "Update member"
      tags:
        - Member
      parameters:
        - name: memberId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMember'
      responses:
        200:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
    get:
      summary: "Read one member"
      description: "Read one member"
      tags:
        - Member
      parameters:
        - name: memberId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
    delete:
      summary: "Delete member"
      description: "Delete member"
      tags:
        - Member
      parameters:
        - name: memberId
          in: path
          required: true
          explode: false
          schema:
            type: string
      responses:
        200:
          description: "OK"
  /api/v1/video:
    get:
      summary: "Read all video (paginated)"
      description: "Read all video (paginated)"
      tags:
        - Video
      parameters:
        - name: size
          in: query
          required: false
          schema:
            type: integer
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Page"
                  - type: object
                    properties:
                      content:
                        type: array
                        items:
                          $ref: "#/components/schemas/Video"
    post:
      summary: "Create video"
      description: "Create video"
      tags:
        - Video
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVideo'
      responses:
        201:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
  /api/v1/video/archive:
    put:
      summary: "Archive videos"
      description: "Archive videos"
      tags:
        - Video
      parameters:
        - name: videoIds
          in: query
          required: true
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: unarchive
          in: query
          description: Defaults to false if no value was provided
          schema:
            type: boolean
            nullable: false
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/v1/video/visible:
    put:
      summary: "Change video visibility"
      description: "Change video visibility"
      tags:
        - Video
      parameters:
        - name: videoIds
          in: query
          required: true
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: visible
          description: Defaults to false if no value was provided
          in: query
          schema:
            type: boolean
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/v1/video/{videoId}:
    put:
      summary: "Update video"
      description: "Update video"
      tags:
        - Video
      parameters:
        - name: videoId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateVideo'
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedVideo'
    get:
      summary: "Read one video"
      description: "Read one video"
      tags:
        - Video
      parameters:
        - name: videoId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedVideo'
    delete:
      summary: "Delete video"
      description: "Delete video"
      tags:
        - Video
      parameters:
        - name: videoId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/v1/videoCrew:
    put:
      summary: "Add position with member to the video"
      description: "Add position with member to the video"
      tags:
        - VideoCrew
      parameters:
        - name: videoId
          in: query
          required: true
          schema:
            type: string
        - name: position
          in: query
          required: true
          schema:
            type: string
        - name: memberId
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedVideo'
        404:
          description: "Not found"
    delete:
      summary: "Delete position with member to the video"
      description: "Delete position with member to the video"
      tags:
        - VideoCrew
      parameters:
        - name: videoId
          in: query
          required: true
          schema:
            type: string
        - name: position
          in: query
          required: true
          schema:
            type: string
        - name: memberId
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedVideo'
        404:
          description: "Not found"
  /api/v1/event:
    get:
      summary: "Read all event"
      description: "Read all event"
      tags:
        - Event
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
    post:
      summary: "Create event"
      description: "Create event"
      tags:
        - Event
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEvent"
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
  /api/v1/event/{eventId}:
    get:
      summary: "Read one event"
      description: "Read one event"
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetailedEvent"
    put:
      summary: "Update event"
      description: "Update event"
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetailedEvent"
    delete:
      summary: "Delete event"
      description: "Delete event"
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: "OK"
  /api/v1/eventVideo:
    put:
      summary: "Add video to event"
      description: "Add video to event"
      tags:
        - EventVideo
      parameters:
        - name: eventId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: videoId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetailedEvent"
    delete:
      summary: "Delete video from event"
      description: "Delete video from event"
      tags:
        - EventVideo
      parameters:
        - name: eventId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: videoId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetailedEvent"
  /api/v1/metrics:
    get:
      summary: "Read metrics"
      description: "Read metrics"
      tags:
        - Metrics
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BssMetrics"
components:
  schemas:
    Sort:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
    Pageable:
      type: object
      properties:
        offset:
          type: integer
        pageNumber:
          type: integer
        pageSize:
          type: integer
        paged:
          type: boolean
        sort:
          $ref: "#/components/schemas/Sort"
    Page:
      type: object
      properties:
        empty:
          type: boolean
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
        numberOfElements:
          type: integer
        pageable:
          $ref: "#/components/schemas/Pageable"
        size:
          type: integer
        sort:
          $ref: "#/components/schemas/Sort"
        totalElements:
          type: integer
        totalPages:
          type: integer
    Status:
      type: string
      nullable: false
      enum:
        - ALUMNI
        - ACTIVE_ALUMNI
        - MEMBER
        - MEMBER_CANDIDATE
        - MEMBER_CANDIDATE_CANDIDATE
    CreateMember:
      type: object
      required:
        - url
        - name
      properties:
        url:
          type: string
          nullable: false
        name:
          type: string
          nullable: false
    UpdateMember:
      type: object
      properties:
        name:
          type: string
          nullable: false
        url:
          type: string
          nullable: false
        description:
          type: string
          nullable: false
        joinedAt:
          type: string
          nullable: false
        role:
          type: string
          nullable: false
        status:
          $ref: '#/components/schemas/Status'
        archived:
          type: boolean
          nullable: false
    Member:
      type: object
      properties:
        id:
          type: string
          nullable: false
        url:
          type: string
          nullable: false
        name:
          type: string
          nullable: false
        description:
          type: string
          nullable: false
        joinedAt:
          type: string
          nullable: false
        role:
          type: string
          nullable: false
        status:
          $ref: '#/components/schemas/Status'
        archived:
          type: boolean
          nullable: false
    CreateVideo:
      type: object
      properties:
        url:
          type: string
          nullable: false
        title:
          type: string
          nullable: false
    UpdateVideo:
      type: object
      properties:
        title:
          type: string
          nullable: false
        description:
          type: string
          nullable: false
        uploadedAt:
          type: string
          format: date
          nullable: false
        visible:
          type: boolean
          nullable: false
        archived:
          type: boolean
          nullable: false
    Video:
      type: object
      properties:
        id:
          type: string
          nullable: false
        url:
          type: string
          nullable: false
        title:
          type: string
          nullable: false
        uploadedAt:
          type: string
          format: date
          nullable: false
        visible:
          type: boolean
          nullable: false
    DetailedVideo:
      allOf:
        - $ref: '#/components/schemas/Video'
        - type: object
          properties:
            description:
              type: string
              nullable: false
            crew:
              type: array
              items:
                $ref: "#/components/schemas/VideoCrew"
    VideoCrew:
      type: object
      properties:
        position:
          type: string
        videoId:
          type: string
          format: uuid
        member:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
              format: uuid
    CreateEvent:
      type: object
      properties:
        url:
          type: string
        title:
          type: string
    DetailedEvent:
      type: object
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        visible:
          type: boolean
        videos:
          type: array
          items:
            $ref: "#/components/schemas/Video"
    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        visible:
          type: boolean
    UpdateEvent:
      type: object
      properties:
        url:
          type: string
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        visible:
          type: boolean
    BssMetrics:
      type: object
      properties:
        videoCount:
          type: integer
        eventCount:
          type: integer
        memberCount:
          type: integer
