version: "3.9"
services:
  app:
    build:
      context: "./"
      dockerfile: "war.Dockerfile"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/postgres?currentSchema=bss_web
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.jpa.open-in-view: false
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
