services:
  app:
    ports: !override
      - "8080"
  postgres:
    ports: !override
      - "5432"
  mock-file-api:
    ports: !override
      - "8080"
    volumes: []
  mock-oidc:
    ports: !override
      - "5556"
