version: "3.9"
services:
  app:
    build:
      context: "./"
    ports:
      - "8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/postgres?currentSchema=bss_web
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.jpa.open-in-view: false
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432"
    healthcheck:
      test: "pg_isready -q"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
