spring:
  application:
    name: BSS Web admin API
  jpa:
    open-in-view: false
  flyway:
    locations:
      - classpath:db/migration/{vendor}
springdoc:
  swagger-ui:
    url: /open-api.yaml
    display-request-duration: true
    use-root-path: true
