name: Release

on:
  pull_request:
  merge_group:
  push:
    branches: [ main ]

permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: release-token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
          permission-contents: write # to be able to publish a GitHub release
          permission-issues: write # to be able to comment on released issues
          permission-pull-requests: write # to be able to comment on released pull requests

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.release-token.outputs.token }}
          fetch-depth: 0
          sparse-checkout: release

      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        with:
          package_json_file: 'release/package.json'

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: 'release/.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'release/pnpm-lock.yaml'

      - run: pnpm install --frozen-lockfile
        working-directory: release

      - run: pnpm run release
        working-directory: release
        env:
          GH_TOKEN: ${{ steps.release-token.outputs.token }}
