name: Release

on:
  pull_request:
  merge_group:
  push:
    branches: [ main ]

permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: release-token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
          permission-contents: write # to be able to publish a GitHub release
          permission-issues: write # to be able to comment on released issues
          permission-pull-requests: write # to be able to comment on released pull requests

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.release-token.outputs.token }}
          fetch-depth: 0
          sparse-checkout: release

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: 'release/package.json'

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'release/.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'release/pnpm-lock.yaml'

      - run: pnpm install --frozen-lockfile
        working-directory: release

      - run: pnpm run release
        working-directory: release
        env:
          GH_TOKEN: ${{ steps.release-token.outputs.token }}
